---
title: "Taller de R: Estadística y Programación"
author: "Taller 3"
date: '09/05/2021'
pagetitle: "Taller 3"
output:
       pdf_document: default
---

<!-- Configuración de la consola de R -->
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = T , eval = T , warning = T)
```

En este taller se evalúan los módulos 4, 5 y 6 del curso. Se presentan 2 tipos de taller (A y B), pero usted solo debe desarrollar 1 de ellos. Para realizar este trabajo, podrá hacer grupo de hasta tres personas. Sea creativo en su código (no hay una respuesta única, todos los métodos que permitan obtener la misma respuesta son validos). Cuando encuentre una ayuda en línea que le permita solucionar algún problema, no olvide citar la fuente. Por último, lea atentamente las instrucciones del taller.

<!------------------->
<!-- Instrucciones -->
<!------------------->

\section{Instrucciones}
\begin{itemize}
\item No seguir las instrucciones tiene una penalización del \textbf{10\%} de la nota total.
\item Este taller representa el 40\% de la nota del curso.
\item El taller estará disponible en SICUA desde las 01:00 horas del 9 de mayo de 2021.
\item Al recibir el taller, uno de los integrantes del grupo debe crear un repositorio llamado \textbf{task-3} para almacenar las respuestas del taller. Este repositorio debe contener como mínimo las siguientes carpetas: \textbf{data}, \textbf{scr} y \textbf{views}. El usuario que crea el repositorio debe invitar como colaborador a los demas integrantes del grupo y al usuario \textcolor{cyan}{\href{https://github.com/eduard-martinez}{eduard-martinez}}.
\item El taller debe ser terminado antes de las 23:59 horas del 1 de junio de 2021. No se calificará ningún commit que sea hecho después de esa fecha.
\item Por favor sea lo más organizado posible y comente paso a paso cada línea de código, pero recuerden \textbf{NO} usar ningún acento o carácter especial dentro del código para evitar problemas al abrir los script en los diferentes sistemas operativos.
\item En las primeras líneas del script debe escribir los nombres y los códigos de las personas que trabajaron en el código.
\item Recuerde que debe elegir y desarrollar solo 1 taller (A o B). 
\end{itemize}

<!-------------->
<!-- Taller A -->
<!-------------->
\begin{center} \textcolor{blue}{\section{Taller A}} \end{center}

# 1. Datos espaciales (50%)

Toda la información empleada en esta parte del taller fue tomada del Marco Geoestadistico Nacional - MGN del DANE. Puede consultar los datos \textcolor{cyan}{\href{https://geoportal.dane.gov.co/servicios/descarga-y-metadatos/descarga-mgn-marco-geoestadistico-nacional/}{aquí}}. 

\textbf{1.1. Importar datos espaciales}

\textbf{1.1.1} De la carpeta \textit{data/outpu} importe los shapefiles de VIAS (llame al objeto \textit{via}) y MGN_URB_TOPONIMIA (llame al objeto \textit{puntos}). El primero contiene las vías del departamento de Norte de Santander y el segundo la ubicación de algunos servicios públicos (hospitales, policía,...) y comerciales (restaurantes, tiendas,...). 

\textbf{1.1.2} Cree un nuevo objeto llamado \textit{c\_medico}, que contenga las observaciones del objeto \textit{puntos} en las que la variable CSIMBOL sea igual a "021001","021002" o "021003". 

\textbf{1.1.3} De la carpeta \textit{data/outpu} importe los \textit{c poblado (2017).rds} (llame al objeto \textit{c\_poblado}), \textit{dp deptos (2017).rds} (llame al objeto \textit{depto}) y \textit{victimas_map-muse.rds} (llame al objeto \textit{mapmuse}). Asegúrese de dejar únicamente los centro poblados con código DANE >= 54001 & < 55000. Además, del objeto \textit{depto}, deje únicamente el polygono del departamento de Norte de Santander.

\textbf{1.2. Atributos de los objetos}

Aplique la función \textit{skim} de la librería \textit{skimr} para explorar todos los objetos cargados en el punto anterior. Si considera necesario, selecciones algunas variables y pinte sobre la consola la tabla de frecuencia estas.

\textbf{1.3. Geometrías del objeto}

\textbf{1.3.1} Para todos los objetos del punto \textit{1.1.}, pinte sobre la consola la caja de coordenadas (st_bbox) y el CRS de cada objeto.

\textbf{1.3.2} Ahora va a reproyectar el CRS de todos los objetos. Asigne la siguiente CRS  \textbf{+proj=utm +zone=19 +datum=WGS84 +units=m +no\_defs} a todos los objetos del punto \textit{1.1.}. 

\textbf{1.4. Operaciones geométricas}

\textbf{1.4.1} Use el objeto \textit{depto} para hacer \textit{cliping} y dejar los puntos de \textit{mapmuse} que están debajo del polígono de Norte de Santander.

\textbf{1.4.2} Del objeto \textit{c\_poblado}, seleccione cualquier municipio, use este polígono y el objeto \textit{via}, para calcular el largo de las vías en el centro poblado que seleccionó.

\textbf{1.5. Pintar mapas}

\textbf{1.5.1} Use la función \textit{leaflet} para visualizar en un mismo mapa: los polígonos de los centros poblados, el polígono del departamento de Norte de Santander y los hospitales y puestos de salud del objeto \textit{c\_medicos}. 

\textbf{1.5.2} Use las librerías \textit{ggplot}, \textit{ggsn} y las demás que considere necesarias para visualizar en un mismo mapa: los polígonos de los centros poblados, el polígono del departamento de Norte de Santander y los hospitales y puestos de salud del objeto \textit{c\_medicos}. Asegúrese de poner la barra de escalas, la estrella del norte y las etiquetas que permitan diferencias cada uno de los objetos. Exporte el mapa en formato .pdf a la carpeta \textit{views}.

# 2. Regresiones (30\%)

La Oficina del Alto Comisionado para la Paz (OACP) tiene el registro oficial de víctimas por minas antipersona (MAP) y municiones sin explosionar (MUSE). Estos registros pueden obtenerse en la página oficial de la \textcolor{cyan}{\href{http://www.accioncontraminas.gov.co/Estadisticas/}{OACP}}. Para este ejercicio usted cuenta con una base de datos que contiene los registros de las victimas de MAP-MUSE en el departamento de Norte de Santander. La variable \textit{fallecido} toma el valor de 1 si la persona fallece en el accidente y 0 si resulta herida.

\textbf{2.1.} Importe el archivo \textit{data/outpu/df\_mapmuse.rds} y estime un modelo de probabilidad lineal en el que fallecido es la variable dependiente. Y use las demás variables como variables explicativas. Almacene los resultados de la estimación en un objeto llamado \textit{ols}.

\textbf{2.2.} Exporte a la carpeta \textit{views} los gráficos con los coeficientes (coef-plot) de las estimaciones.

\textbf{2.3.} Ahora estime la ecuación del punto \textit{2.1.} usando un modelo logit y un modelo probit, almacene los resultados de las estimaciones en dos objetos llamados \textit{logit} y \textit{probit} respectivamente.

\textbf{2.4.} Exporte los resultados de los tres modelos en una misma tabla usando la función \textit{outreg}.

\textbf{2.5.} De los objetos \textit{logit} y \textit{probit} exporte a la carpeta \textit{views} dos gráficos con el efecto marginal de la distancia a un centro medico sobre la probabilidad de fallecer.

# 3. Web-scraping (10%)

\textbf{3.1.} Desde la consola de Rstudio lea la siguiente url \textcolor{cyan}{\href{https://es.wikipedia.org/wiki/Departamentos_de_Colombia}{https://es.wikipedia.org/wiki/Departamentos\_de\_Colombia}} y cree un objeto que contenga el HTML de la página como un objeto \textit{xml\_document}.

\textbf{3.2.} Use el \textit{xpath} para extraer el título de la página (Departamentos de Colombia).

\textbf{3.3.} Extraiga la tabla que contiene los departamentos de Colombia.

<!-------------->
<!-- Taller B -->
<!-------------->
\begin{center} \textcolor{blue}{\section{Taller B}} \end{center}

# 1. Datos espaciales (40%)

Toda la información empleada en esta parte del taller fue tomada del Marco Geoestadistico Nacional - MGN del DANE. Puede consultar los datos \textcolor{cyan}{\href{https://geoportal.dane.gov.co/servicios/descarga-y-metadatos/descarga-mgn-marco-geoestadistico-nacional/}{aquí}}. 

\textbf{1.1. Importar datos espaciales}

\textbf{1.1.1} De la carpeta \textit{data/outpu} importe los shapefiles de VIAS (llame al objeto \textit{via}) y MGN_URB_TOPONIMIA (llame al objeto \textit{puntos}). El primero contiene las vías del departamento de Norte de Santander y el segundo la ubicación de algunos servicios públicos (hospitales, policía,...) y comerciales (restaurantes, tiendas,...). 

\textbf{1.1.2} Cree un nuevo objeto llamado \textit{c\_medico}, que contenga las observaciones del objeto \textit{puntos} en las que la variable CSIMBOL sea igual a "021001","021002" o "021003". 

\textbf{1.1.3} De la carpeta \textit{data/outpu} importe los \textit{c poblado (2017).rds} (llame al objeto \textit{c\_poblado}), \textit{dp deptos (2017).rds} (llame al objeto \textit{depto}) y \textit{victimas_map-muse.rds} (llame al objeto \textit{mapmuse}). Asegúrese de dejar únicamente los centro poblados con código DANE >= 54001 & < 55000. Además, del objeto \textit{depto}, deje únicamente el polygono del departamento de Norte de Santander.

\textbf{1.2. Atributos de los objetos}

Aplique la función \textit{skim} de la librería \textit{skimr} para explorar todos los objetos cargados en el punto anterior. Si considera necesario, selecciones algunas variables y pinte sobre la consola la tabla de frecuencia estas.

\textbf{1.3. Geometrías del objeto}

\textbf{1.3.1} Para todos los objetos del punto \textit{1.1.}, pinte sobre la consola la caja de coordenadas (st_bbox) y el CRS de cada objeto.

\textbf{1.3.2} Ahora va a reproyectar el CRS de todos los objetos. Asigne la siguiente CRS \textbf{+proj=utm +zone=19 +datum=WGS84 +units=m +no\_defs} a todos los objetos del punto \textit{1.1.}. 

\textbf{1.4. Operaciones geométricas}

\textbf{1.4.1} Use el objeto \textit{depto} para hacer \textit{cliping} y dejar los puntos de \textit{mapmuse} que están debajo del polígono de Norte de Santander.

\textbf{1.4.2} Del objeto \textit{c\_poblado}, seleccione cualquier municipio, use este polígono y el objeto \textit{via}, para calcular el largo de las vías en el centro poblado que seleccionó.

\textbf{1.5. Pintar mapas}

\textbf{1.5.1} Use la función \textit{leaflet} para visualizar en un mismo mapa: los polígonos de los centros poblados, el polígono del departamento de Norte de Santander y los hospitales y puestos de salud del objeto \textit{c\_medicos}. 

\textbf{1.5.2} Use las librerías \textit{ggplot}, \textit{ggsn} y las demás que considere necesarias para visualizar en un mismo mapa: los polígonos de los centros poblados, el polígono del departamento de Norte de Santander y los hospitales y puestos de salud del objeto \textit{c\_medicos}. Asegúrese de poner la barra de escalas, la estrella del norte y las etiquetas que permitan diferencias cada uno de los objetos. Exporte el mapa en formato .pdf a la carpeta \textit{views}.

# 2. Regresiones (45\%)

La Oficina del Alto Comisionado para la Paz (OACP) tiene el registro oficial de víctimas por minas antipersona (MAP) y municiones sin explosionar (MUSE). Estos registros pueden obtenerse en la página oficial de la \textcolor{cyan}{\href{http://www.accioncontraminas.gov.co/Estadisticas/}{OACP}}. Para este ejercicio usted cuenta con una base de datos que contiene los registros de las victimas de MAP-MUSE en el departamento de Norte de Santander. 

\textbf{2.0.} En este punto usted debe emplear el objeto \textit{mapmuse} y calcular la distancia más cercana de cada punto a una \textit{via}, un centro medico (\textit{c\_medico}) y a un centro poblado (\textit{c\_poblado}). Asegurese de nombrar las variables de distancia dist\_vias, dist\_cmedico y dist\_cpoblado, respectivamente. Construya la variable \textit{fallecido} que tome el valor de 1 si el estado de la victima es muerta y 0 si el estado es herida. Finalmente convierta el objeto en un \textit{data.frame} solamente y elimine las variables \textit{estado}, \textit{month} y \textit{geometry}. 

\textbf{2.1.} Estime un modelo de probabilidad lineal en el que fallecido es la variable dependiente. Y use las demás variables como variables explicativas. Almacene los resultados de la estimación en un objeto llamado \textit{ols}.

\textbf{2.2.} Exporte a la carpeta \textit{views} los gráficos con los coeficientes (coef-plot) de las estimaciones.

\textbf{2.3.} Ahora estime la ecuación del punto \textit{2.1.} usando un modelo logit y un modelo probit, almacene los resultados de las estimaciones en dos objetos llamados \textit{logit} y \textit{probit} respectivamente.

\textbf{2.4.} Exporte los resultados de los tres modelos en una misma tabla usando la función \textit{outreg}.

\textbf{2.5.} De los objetos \textit{logit} y \textit{probit} exporte a la carpeta \textit{views} dos gráficos con el efecto marginal de la distancia a un centro medico sobre la probabilidad de fallecer.

# 3. Web-scraping (5%)

\textbf{3.1.} Desde la consola de Rstudio lea la siguiente url \textcolor{cyan}{\href{https://es.wikipedia.org/wiki/Departamentos_de_Colombia}{https://es.wikipedia.org/wiki/Departamentos\_de\_Colombia}} y cree un objeto que contenga el HTML de la página como un objeto \textit{xml\_document}.

\textbf{3.2.} Use el \textit{xpath} para extraer el título de la página (Departamentos de Colombia).

\textbf{3.3.} Extraiga la tabla que contiene los departamentos de Colombia.

